development:
  adapter: mysql
  encoding: utf8
  database: mellterm
  username: root
  password:
  socket:  /opt/local/var/run/mysql5/mysqld.sock


test:
  adapter: mysql
  encoding: utf8
  database: mellterm_test
  username: root
  password:
  socket:  /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: mellterm
  username: root
  password: 
  socket:  /opt/local/var/run/mysql5/mysqld.sock
